app:
  domain: "xxxexample.com"
  port: "25565"
  uuid: "2584b733-9095-4bec-a7d5-62b473540f7a"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: ""
  argo-token: ""
  remarks-prefix: ""
